### ISSUE TITLE
Expected error

### ISSUE THREAD

**Issue by Malkavianson** [kunalnagarco/imdb-scraper#140]
## I cannot start it =(

![image](https://user-images.githubusercontent.com/63012624/200608648-d4d6f7e8-11bf-4c62-b831-f5f8966fdedb.png)

I dont know what it means XD

Help please :'(

**Comment by kunalnagar** [comment]
@Malkavianson - i see that you're running `yarn build` - this command builds the project

Please run `yarn install` to install the dependencies and then `yarn start` to start the project

**Comment by Malkavianson** [comment]
> @Malkavianson - i see that you're running `yarn build` - this command builds the project
> 
> Please run `yarn install` to install the dependencies and then `yarn start` to start the project

😅 I'm sorry 
LoL 
Jr mistake
